
version: 2

models:
  - name: airline
    description: "List of airline names along with their IATA codes"
    columns:
      - name: iata_code
        data_type: string
        description: ""

      - name: airline_name
        data_type: string
        description: "Name of the Airlines"

  - name: fact_status
    description: ""
    columns:
      - name: fl_date
        data_type: string
        description: ""

      - name: flight_day
        data_type: int64
        description: ""

      - name: flight_month
        data_type: int64
        description: ""

      - name: op_carrier
        data_type: string
        description: ""

      - name: op_carrier_fl_num
        data_type: int64
        description: ""

      - name: origin
        data_type: string
        description: ""

      - name: dest
        data_type: string
        description: ""

      - name: crs_dep_time
        data_type: int64
        description: ""

      - name: dep_time
        data_type: float64
        description: ""

      - name: dep_delay
        data_type: float64
        description: ""

      - name: taxi_out
        data_type: float64
        description: ""

      - name: wheels_off
        data_type: float64
        description: ""

      - name: wheels_on
        data_type: float64
        description: ""

      - name: taxi_in
        data_type: float64
        description: ""

      - name: crs_arr_time
        data_type: int64
        description: ""

      - name: arr_time
        data_type: float64
        description: ""

      - name: arr_delay
        data_type: float64
        description: ""

      - name: cancelled
        data_type: float64
        description: ""

      - name: diverted
        data_type: float64
        description: ""

      - name: crs_elapsed_time
        data_type: float64
        description: ""

      - name: actual_elapsed_time
        data_type: float64
        description: ""

      - name: air_time
        data_type: float64
        description: ""

      - name: distance
        data_type: float64
        description: ""

      - name: airline_iata_code
        data_type: string
        description: ""

      - name: airline_name
        data_type: string
        description: ""

      - name: origin_airport_iata_code
        data_type: string
        description: ""

      - name: origin_airport_name
        data_type: string
        description: ""

      - name: origin_city
        data_type: string
        description: ""

      - name: origin_state
        data_type: string
        description: ""

      - name: origin_country
        data_type: string
        description: ""

      - name: origin_latitude
        data_type: float64
        description: ""

      - name: origin_longitude
        data_type: float64
        description: ""

      - name: destination_airport_iata_code
        data_type: string
        description: ""

      - name: destination_airport_name
        data_type: string
        description: ""

      - name: destination_city
        data_type: string
        description: ""

      - name: destination_state
        data_type: string
        description: ""

      - name: destination_country
        data_type: string
        description: ""

      - name: destination_latitude
        data_type: float64
        description: ""

      - name: destination_longitude
        data_type: float64
        description: ""

  - name: airport
    description: ""
    columns:
      - name: iata_code
        data_type: string
        description: ""

      - name: airport_name
        data_type: string
        description: ""

      - name: city
        data_type: string
        description: ""

      - name: state
        data_type: string
        description: ""

      - name: country
        data_type: string
        description: ""

      - name: latitude
        data_type: float64
        description: ""

      - name: longitude
        data_type: float64
        description: ""
